# AUTO-GENERATED by tools/checkspecs.py - DO NOT EDIT
from .....testing import assert_equal
from ..specialized import ESLR


def test_ESLR_inputs():
    input_map = dict(args=dict(argstr='%s',
    ),
    closingSize=dict(argstr='--closingSize %d',
    ),
    high=dict(argstr='--high %d',
    ),
    inputVolume=dict(argstr='--inputVolume %s',
    ),
    low=dict(argstr='--low %d',
    ),
    numberOfThreads=dict(argstr='--numberOfThreads %d',
    ),
    openingSize=dict(argstr='--openingSize %d',
    ),
    outputVolume=dict(argstr='--outputVolume %s',
    hash_files=False,
    ),
    preserveOutside=dict(argstr='--preserveOutside ',
    ),
    safetySize=dict(argstr='--safetySize %d',
    ),
    )
    inputs = ESLR._input_spec()

    for key, metadata in list(input_map.items()):
        for metakey, value in list(metadata.items()):
            yield assert_equal, getattr(inputs.traits()[key], metakey), value


def test_ESLR_outputs():
    output_map = dict(outputVolume=dict(),
    )
    outputs = ESLR._output_spec()

    for key, metadata in list(output_map.items()):
        for metakey, value in list(metadata.items()):
            yield assert_equal, getattr(outputs.traits()[key], metakey), value
