# AUTO-GENERATED by tools/checkspecs.py - DO NOT EDIT
from nipype.testing import assert_equal
from nipype.interfaces.fsl.preprocess import BETSurface

def test_BETSurface_inputs():
    input_map = dict(args=dict(argstr='%s',
    ),
    environ=dict(nohash=True,
    usedefault=True,
    ),
    ignore_exception=dict(nohash=True,
    usedefault=True,
    ),
    mask=dict(argstr='--mask',
    position=3,
    ),
    meshfile=dict(argstr='%s',
    position=-3,
    ),
    out_basename=dict(argstr='%s',
    genfile=True,
    position=-1,
    ),
    outline=dict(argstr='--outline',
    position=2,
    ),
    output_type=dict(),
    retesellate_mesh=dict(argstr='--increased_precision %d',
    position=5,
    ),
    skullmask=dict(argstr='--skull mask',
    ddesc='Generates skull binary mask',
    position=4,
    ),
    t1_file=dict(argstr='%s',
    mandatory=True,
    position=-5,
    ),
    t1_only=dict(argstr='--t1only',
    position=0,
    ),
    t1_to_standard_matrix=dict(argstr='%s',
    mandatory=True,
    position=-2,
    ),
    t2_file=dict(argstr='%s',
    position=-4,
    ),
    terminal_output=dict(mandatory=True,
    nohash=True,
    ),
    )
    inputs = BETSurface.input_spec()

    for key, metadata in input_map.items():
        for metakey, value in metadata.items():
            yield assert_equal, getattr(inputs.traits()[key], metakey), value

def test_BETSurface_outputs():
    output_map = dict(inskull_mask_file=dict(),
    inskull_mesh_file=dict(),
    inskull_mesh_outline_file=dict(),
    outskin_mask_file=dict(),
    outskin_mesh_file=dict(),
    outskin_mesh_outline_file=dict(),
    outskull_mask_file=dict(),
    outskull_mesh_file=dict(),
    outskull_mesh_outline_file=dict(),
    skull_mask_file=dict(),
    )
    outputs = BETSurface.output_spec()

    for key, metadata in output_map.items():
        for metakey, value in metadata.items():
            yield assert_equal, getattr(outputs.traits()[key], metakey), value

