# AUTO-GENERATED by tools/checkspecs.py - DO NOT EDIT
from nipype.testing import assert_equal
from nipype.interfaces.fsl.maths import SpatialFilter
def test_SpatialFilter_inputs():
    input_map = dict(ignore_exception=dict(nohash=True,
    usedefault=True,
    ),
    nan2zeros=dict(position=3,
    argstr='-nan',
    ),
    kernel_file=dict(position=5,
    xor=['kernel_size'],
    argstr='%s',
    ),
    out_file=dict(hash_files=False,
    genfile=True,
    position=-2,
    argstr='%s',
    ),
    args=dict(argstr='%s',
    ),
    internal_datatype=dict(position=1,
    argstr='-dt %s',
    ),
    terminal_output=dict(mandatory=True,
    nohash=True,
    ),
    environ=dict(nohash=True,
    usedefault=True,
    ),
    kernel_shape=dict(position=4,
    argstr='-kernel %s',
    ),
    output_type=dict(),
    operation=dict(position=6,
    mandatory=True,
    argstr='-f%s',
    ),
    output_datatype=dict(position=-1,
    argstr='-odt %s',
    ),
    kernel_size=dict(position=5,
    xor=['kernel_file'],
    argstr='%.4f',
    ),
    in_file=dict(position=2,
    mandatory=True,
    argstr='%s',
    ),
    )
    inputs = SpatialFilter.input_spec()

    for key, metadata in input_map.items():
        for metakey, value in metadata.items():
            yield assert_equal, getattr(inputs.traits()[key], metakey), value
def test_SpatialFilter_outputs():
    output_map = dict(out_file=dict(),
    )
    outputs = SpatialFilter.output_spec()

    for key, metadata in output_map.items():
        for metakey, value in metadata.items():
            yield assert_equal, getattr(outputs.traits()[key], metakey), value
