# AUTO-GENERATED by tools/checkspecs.py - DO NOT EDIT
from nipype.testing import assert_equal
from nipype.interfaces.fsl.utils import ImageMeants
def test_ImageMeants_inputs():
    input_map = dict(ignore_exception=dict(nohash=True,
    usedefault=True,
    ),
    nobin=dict(argstr='--no_bin',
    ),
    show_all=dict(argstr='--showall',
    ),
    out_file=dict(hash_files=False,
    genfile=True,
    argstr='-o %s',
    ),
    mask=dict(argstr='-m %s',
    ),
    args=dict(argstr='%s',
    ),
    transpose=dict(argstr='--transpose',
    ),
    terminal_output=dict(mandatory=True,
    nohash=True,
    ),
    environ=dict(nohash=True,
    usedefault=True,
    ),
    in_file=dict(position=0,
    mandatory=True,
    argstr='-i %s',
    ),
    eig=dict(argstr='--eig',
    ),
    output_type=dict(),
    use_mm=dict(argstr='--usemm',
    ),
    order=dict(usedefault=True,
    argstr='--order=%d',
    ),
    spatial_coord=dict(argstr='-c %s',
    ),
    )
    inputs = ImageMeants.input_spec()

    for key, metadata in input_map.items():
        for metakey, value in metadata.items():
            yield assert_equal, getattr(inputs.traits()[key], metakey), value
def test_ImageMeants_outputs():
    output_map = dict(out_file=dict(),
    )
    outputs = ImageMeants.output_spec()

    for key, metadata in output_map.items():
        for metakey, value in metadata.items():
            yield assert_equal, getattr(outputs.traits()[key], metakey), value
