# Read the Docs configuration file
# See https://docs.readthedocs.io/en/stable/config-file/v2.html for details

# Required
version: 2

# Set the OS, Python version and other tools you might need
build:
  os: ubuntu-lts-latest
  tools:
    python: "3.13"
  jobs:
    pre_create_environment:
      - asdf plugin add uv
      - asdf install uv latest
      - asdf global uv latest
    create_environment:
      - uv venv $READTHEDOCS_VIRTUALENV_PATH
    install:
      - >
        VIRTUAL_ENV=$READTHEDOCS_VIRTUALENV_PATH
        UV_CACHE_DIR=$READTHEDOCS_VIRTUALENV_PATH/../../uv_cache
        uv sync --active --extra=doc

# Build documentation in the docs/ directory with Sphinx
sphinx:
  configuration: doc/conf.py

# Optionally build your docs in additional formats such as PDF and ePub
formats:
  - htmlzip
