coverage:
  range: "0...100"
  status:
    project:
      default:
        target: 0
        threshold: 100
      patch: false
      unittests:
        target: 0
        threshold: 100
        flags:
          - "unittests"
      smoketests:
        target: 0
        threshold: 100
        flags:
          - "smoketests"
