# AUTO-GENERATED by tools/checkspecs.py - DO NOT EDIT
from nipype.testing import assert_equal
from nipype.interfaces.spm.preprocess import DARTELNorm2MNI
def test_DARTELNorm2MNI_inputs():
    input_map = dict(ignore_exception=dict(nohash=True,
    usedefault=True,
    ),
    paths=dict(),
    voxel_size=dict(field='mni_norm.vox',
    ),
    template_file=dict(copyfile=False,
    mandatory=True,
    field='mni_norm.template',
    ),
    use_v8struct=dict(min_ver='8',
    usedefault=True,
    ),
    flowfield_files=dict(field='mni_norm.data.subjs.flowfields',
    mandatory=True,
    ),
    use_mcr=dict(),
    bounding_box=dict(field='mni_norm.bb',
    ),
    mfile=dict(usedefault=True,
    ),
    matlab_cmd=dict(),
    apply_to_files=dict(copyfile=False,
    mandatory=True,
    field='mni_norm.data.subjs.images',
    ),
    fwhm=dict(field='mni_norm.fwhm',
    ),
    modulate=dict(field='mni_norm.preserve',
    ),
    )
    inputs = DARTELNorm2MNI.input_spec()

    for key, metadata in input_map.items():
        for metakey, value in metadata.items():
            yield assert_equal, getattr(inputs.traits()[key], metakey), value
def test_DARTELNorm2MNI_outputs():
    output_map = dict(normalized_files=dict(),
    normalization_parameter_file=dict(),
    )
    outputs = DARTELNorm2MNI.output_spec()

    for key, metadata in output_map.items():
        for metakey, value in metadata.items():
            yield assert_equal, getattr(outputs.traits()[key], metakey), value
