# AUTO-GENERATED by tools/checkspecs.py - DO NOT EDIT
from nipype.testing import assert_equal
from nipype.algorithms.misc import NormalizeMaps

def test_NormalizeMaps_inputs():
    input_map = dict(in_files=dict(),
    in_mask=dict(mandatory=False,
    ),
    )
    inputs = NormalizeMaps.input_spec()

    for key, metadata in input_map.items():
        for metakey, value in metadata.items():
            yield assert_equal, getattr(inputs.traits()[key], metakey), value

def test_NormalizeMaps_outputs():
    output_map = dict(out_files=dict(),
    )
    outputs = NormalizeMaps.output_spec()

    for key, metadata in output_map.items():
        for metakey, value in metadata.items():
            yield assert_equal, getattr(outputs.traits()[key], metakey), value

