# AUTO-GENERATED by tools/checkspecs.py - DO NOT EDIT
from nipype.testing import assert_equal
from nipype.algorithms.misc import Matlab2CSV
def test_Matlab2CSV_inputs():
    input_map = dict(reshape_matrix=dict(usedefault=True,
    ),
    in_file=dict(mandatory=True,
    ),
    )
    inputs = Matlab2CSV.input_spec()

    for key, metadata in input_map.items():
        for metakey, value in metadata.items():
            yield assert_equal, getattr(inputs.traits()[key], metakey), value
def test_Matlab2CSV_outputs():
    output_map = dict(csv_files=dict(),
    )
    outputs = Matlab2CSV.output_spec()

    for key, metadata in output_map.items():
        for metakey, value in metadata.items():
            yield assert_equal, getattr(outputs.traits()[key], metakey), value
