# AUTO-GENERATED by tools/checkspecs.py - DO NOT EDIT
from ...testing import assert_equal
from ..misc import PickAtlas


def test_PickAtlas_inputs():
    input_map = dict(atlas=dict(mandatory=True,
    ),
    dilation_size=dict(usedefault=True,
    ),
    hemi=dict(usedefault=True,
    ),
    labels=dict(mandatory=True,
    ),
    mask_file=dict(ns='atlas',
    ),
    output_file=dict(deprecated=True,
    new_name='mask_file',
    ),
    )
    inputs = PickAtlas._input_spec()

    for key, metadata in list(input_map.items()):
        for metakey, value in list(metadata.items()):
            yield assert_equal, getattr(inputs.traits()[key], metakey), value


def test_PickAtlas_outputs():
    output_map = dict(mask_file=dict(),
    )
    outputs = PickAtlas._output_spec()

    for key, metadata in list(output_map.items()):
        for metakey, value in list(metadata.items()):
            yield assert_equal, getattr(outputs.traits()[key], metakey), value
