# AUTO-GENERATED by tools/checkspecs.py - DO NOT EDIT
from nipype.testing import assert_equal
from nipype.algorithms.icc import ICC
def test_ICC_inputs():
    input_map = dict(ignore_exception=dict(nohash=True,
    usedefault=True,
    ),
    mask=dict(mandatory=True,
    ),
    subjects_sessions=dict(mandatory=True,
    ),
    )
    inputs = ICC.input_spec()

    for key, metadata in input_map.items():
        for metakey, value in metadata.items():
            yield assert_equal, getattr(inputs.traits()[key], metakey), value
def test_ICC_outputs():
    output_map = dict(session_var_map=dict(),
    icc_map=dict(),
    subject_var_map=dict(),
    )
    outputs = ICC.output_spec()

    for key, metadata in output_map.items():
        for metakey, value in metadata.items():
            yield assert_equal, getattr(outputs.traits()[key], metakey), value
