# AUTO-GENERATED by tools/checkspecs.py - DO NOT EDIT
from nipype.testing import assert_equal
from nipype.interfaces.slicer.filtering.extractskeleton import ExtractSkeleton
def test_ExtractSkeleton_inputs():
    input_map = dict(ignore_exception=dict(nohash=True,
    usedefault=True,
    ),
    OutputImageFileName=dict(position=-1,
    hash_files=False,
    argstr='%s',
    ),
    args=dict(argstr='%s',
    ),
    numPoints=dict(argstr='--numPoints %d',
    ),
    InputImageFileName=dict(position=-2,
    argstr='%s',
    ),
    pointsFile=dict(argstr='--pointsFile %s',
    ),
    terminal_output=dict(mandatory=True,
    nohash=True,
    ),
    environ=dict(nohash=True,
    usedefault=True,
    ),
    dontPrune=dict(argstr='--dontPrune ',
    ),
    type=dict(argstr='--type %s',
    ),
    )
    inputs = ExtractSkeleton.input_spec()

    for key, metadata in input_map.items():
        for metakey, value in metadata.items():
            yield assert_equal, getattr(inputs.traits()[key], metakey), value
def test_ExtractSkeleton_outputs():
    output_map = dict(OutputImageFileName=dict(position=-1,
    ),
    )
    outputs = ExtractSkeleton.output_spec()

    for key, metadata in output_map.items():
        for metakey, value in metadata.items():
            yield assert_equal, getattr(outputs.traits()[key], metakey), value
