# AUTO-GENERATED by tools/checkspecs.py - DO NOT EDIT
from nipype.testing import assert_equal
from nipype.interfaces.slicer.filtering.imagelabelcombine import ImageLabelCombine
def test_ImageLabelCombine_inputs():
    input_map = dict(ignore_exception=dict(nohash=True,
    usedefault=True,
    ),
    OutputLabelMap=dict(position=-1,
    hash_files=False,
    argstr='%s',
    ),
    args=dict(argstr='%s',
    ),
    terminal_output=dict(mandatory=True,
    nohash=True,
    ),
    environ=dict(nohash=True,
    usedefault=True,
    ),
    InputLabelMap_A=dict(position=-3,
    argstr='%s',
    ),
    InputLabelMap_B=dict(position=-2,
    argstr='%s',
    ),
    first_overwrites=dict(argstr='--first_overwrites ',
    ),
    )
    inputs = ImageLabelCombine.input_spec()

    for key, metadata in input_map.items():
        for metakey, value in metadata.items():
            yield assert_equal, getattr(inputs.traits()[key], metakey), value
def test_ImageLabelCombine_outputs():
    output_map = dict(OutputLabelMap=dict(position=-1,
    ),
    )
    outputs = ImageLabelCombine.output_spec()

    for key, metadata in output_map.items():
        for metakey, value in metadata.items():
            yield assert_equal, getattr(outputs.traits()[key], metakey), value
