# AUTO-GENERATED by tools/checkspecs.py - DO NOT EDIT
from .....testing import assert_equal
from ..histogrammatching import HistogramMatching


def test_HistogramMatching_inputs():
    input_map = dict(args=dict(argstr='%s',
    ),
    environ=dict(nohash=True,
    usedefault=True,
    ),
    ignore_exception=dict(nohash=True,
    usedefault=True,
    ),
    inputVolume=dict(argstr='%s',
    position=-3,
    ),
    numberOfHistogramLevels=dict(argstr='--numberOfHistogramLevels %d',
    ),
    numberOfMatchPoints=dict(argstr='--numberOfMatchPoints %d',
    ),
    outputVolume=dict(argstr='%s',
    hash_files=False,
    position=-1,
    ),
    referenceVolume=dict(argstr='%s',
    position=-2,
    ),
    terminal_output=dict(nohash=True,
    ),
    threshold=dict(argstr='--threshold ',
    ),
    )
    inputs = HistogramMatching.input_spec()

    for key, metadata in list(input_map.items()):
        for metakey, value in list(metadata.items()):
            yield assert_equal, getattr(inputs.traits()[key], metakey), value


def test_HistogramMatching_outputs():
    output_map = dict(outputVolume=dict(position=-1,
    ),
    )
    outputs = HistogramMatching.output_spec()

    for key, metadata in list(output_map.items()):
        for metakey, value in list(metadata.items()):
            yield assert_equal, getattr(outputs.traits()[key], metakey), value
