# emacs: -*- mode: python; py-indent-offset: 4; indent-tabs-mode: nil -*-
# vi: set ft=python sts=4 ts=4 sw=4 et:
"""MRtrix top level namespace
dir2amp	convert directions image to amplitudes.
disp_profile	view spherical harmonics surface plots.
erode	erode (or dilate) mask (i.e. binary) image
find_SH_peaks	identify the orientations of the N largest peaks of a SH profile
gen_ROI	generate a mask ROI with the same dimensions as the input dataset, and all voxel values set to one in the regions specified
gen_unit_warp	generate a warp field corresponding to a no-warp operation. This is useful to obtain the warp fields from other normalisation applications, by applying the warp of interest to the the warp field generated by this program.
import_tracks	convert ascii track files into MRtrix format.
mrstats	compute images statistics.
mrtransform	apply spatial transformations or reslice images.
normalise_tracks	apply a normalisation map to a tracks file.
resample_tracks	Resample tracks so they all have the same number of samples, spaced at constant intervals within the range specified.
sample_tracks	sample image intensity values along the tracks, producing one intensity value per point along each track.
sdeconv	perform linear spherical deconvolution.
streamtrack	perform streamlines tracking.
tensor_metric	generate maps of tensor-derived parameters.
threshold	create bitwise image by thresholding image intensity.
truncate_tracks	truncate a tracks file by selecting only the first N tracks.
"""

from nipype.interfaces.mrtrix.tracking import (Tracks2Prob, StreamlineTrack,
DiffusionTensorStreamlineTrack, SphericallyDeconvolutedStreamlineTrack, ProbabilisticSphericallyDeconvolutedStreamlineTrack)
from nipype.interfaces.mrtrix.tensors import FSL2MRTrix, ConstrainedSphericalDeconvolution, DWI2SphericalHarmonicsImage, EstimateResponseForSH
from nipype.interfaces.mrtrix.preprocess import (MRConvert, MRMultiply, MRTrixViewer, MRTrixInfo, GenerateWhiteMatterMask, DWI2Tensor,
Tensor2ApparentDiffusion, Tensor2FractionalAnisotropy, Tensor2Vector)

import nose

