# AUTO-GENERATED by tools/checkspecs.py - DO NOT EDIT
from nipype.testing import assert_equal
from nipype.interfaces.camino.dti import TrackBootstrap
def test_TrackBootstrap_inputs():
    input_map = dict(bsdatafiles=dict(mandatory=True,
    argstr='-bsdatafile %s',
    ),
    iterations=dict(units='NA',
    argstr='-iterations %d',
    ),
    numpds=dict(units='NA',
    argstr='-numpds %d',
    ),
    data_dims=dict(units='voxels',
    argstr='-datadims %s',
    ),
    outputtracts=dict(argstr='-outputtracts %s',
    ),
    scheme_file=dict(mandatory=True,
    argstr='-schemefile %s',
    ),
    seed_file=dict(position=2,
    argstr='-seedfile %s',
    ),
    maxcomponents=dict(units='NA',
    argstr='-maxcomponents %d',
    ),
    in_file=dict(position=1,
    mandatory=True,
    argstr='-inputfile %s',
    ),
    ipthresh=dict(argstr='-ipthresh %f',
    ),
    voxel_dims=dict(units='mm',
    argstr='-voxeldims %s',
    ),
    output_root=dict(position=-1,
    argstr='-outputroot %s',
    ),
    ignore_exception=dict(nohash=True,
    usedefault=True,
    ),
    args=dict(argstr='%s',
    ),
    inputmodel=dict(usedefault=True,
    argstr='-inputmodel %s',
    ),
    terminal_output=dict(mandatory=True,
    nohash=True,
    ),
    anisfile=dict(argstr='-anisfile %s',
    ),
    inversion=dict(argstr='-inversion %s',
    ),
    out_file=dict(position=-1,
    genfile=True,
    argstr='-outputfile %s',
    ),
    curvethresh=dict(argstr='-curvethresh %f',
    ),
    inputdatatype=dict(argstr='-inputdatatype %s',
    ),
    environ=dict(nohash=True,
    usedefault=True,
    ),
    gzip=dict(argstr='-gzip',
    ),
    bgmask=dict(argstr='-bgmask %s',
    ),
    anisthresh=dict(argstr='-anisthresh %f',
    ),
    )
    inputs = TrackBootstrap.input_spec()

    for key, metadata in input_map.items():
        for metakey, value in metadata.items():
            yield assert_equal, getattr(inputs.traits()[key], metakey), value
def test_TrackBootstrap_outputs():
    output_map = dict(tracked=dict(),
    )
    outputs = TrackBootstrap.output_spec()

    for key, metadata in output_map.items():
        for metakey, value in metadata.items():
            yield assert_equal, getattr(outputs.traits()[key], metakey), value
