# AUTO-GENERATED by tools/checkspecs.py - DO NOT EDIT
from nipype.testing import assert_equal
from nipype.interfaces.camino.dti import ComputeEigensystem
def test_ComputeEigensystem_inputs():
    input_map = dict(ignore_exception=dict(nohash=True,
    usedefault=True,
    ),
    out_file=dict(position=-1,
    genfile=True,
    argstr='> %s',
    ),
    inputmodel=dict(argstr='-inputmodel %s',
    ),
    outputdatatype=dict(usedefault=True,
    argstr='-outputdatatype %s',
    ),
    args=dict(argstr='%s',
    ),
    inputdatatype=dict(usedefault=True,
    argstr='-inputdatatype %s',
    ),
    maxcomponents=dict(argstr='-maxcomponents %d',
    ),
    environ=dict(nohash=True,
    usedefault=True,
    ),
    in_file=dict(position=1,
    mandatory=True,
    argstr='< %s',
    ),
    terminal_output=dict(mandatory=True,
    nohash=True,
    ),
    )
    inputs = ComputeEigensystem.input_spec()

    for key, metadata in input_map.items():
        for metakey, value in metadata.items():
            yield assert_equal, getattr(inputs.traits()[key], metakey), value
def test_ComputeEigensystem_outputs():
    output_map = dict(eigen=dict(),
    )
    outputs = ComputeEigensystem.output_spec()

    for key, metadata in output_map.items():
        for metakey, value in metadata.items():
            yield assert_equal, getattr(outputs.traits()[key], metakey), value
