fprintf(1,'Executing %s at %s:\n',mfilename,datestr(now));
ver,
try,

        %% Generated by nipype.interfaces.spm
        if isempty(which('spm')),
             throw(MException('SPMCheck:NotFound','SPM not in matlab path'));
        end
        fprintf('SPM version: %s\n',spm('ver'));
        fprintf('SPM path: %s\n',which('spm'));
        spm_defaults;
                  
        if strcmp(spm('ver'),'SPM8'), spm_jobman('initcfg');end

        jobs{1}.tools{1}.preproc8(1).channel(1).biasreg = 0.0001;
jobs{1}.tools{1}.preproc8(1).channel(1).write(1) = 0;
jobs{1}.tools{1}.preproc8(1).channel(1).write(2) = 0;
jobs{1}.tools{1}.preproc8(1).channel(1).biasfwhm = 60.0;
jobs{1}.tools{1}.preproc8(1).channel(1).vols = {...
'/home/filo/data/anonymised/coD136_anont1mprnssagp2iso.nii,1';...
};
 
        if strcmp(spm('ver'),'SPM8'), 
           jobs=spm_jobman('spm5tospm8',{jobs});
        end 
        spm_jobman('run',jobs);

        
,catch ME,
ME,
ME.stack,
fprintf('%s\n',ME.message);
fprintf(2,'<MatlabScriptException>');
fprintf(2,'%s\n',ME.message);
fprintf(2,'File:%s\nName:%s\nLine:%d\n',ME.stack.file,ME.stack.name,ME.stack.line);
fprintf(2,'</MatlabScriptException>');
end;
