# AUTO-GENERATED by tools/checkspecs.py - DO NOT EDIT
from nipype.testing import assert_equal
from nipype.interfaces.diffusion_toolkit.odf import HARDIMat
def test_HARDIMat_inputs():
    input_map = dict(ignore_exception=dict(nohash=True,
    usedefault=True,
    ),
    bvecs=dict(position=1,
    mandatory=True,
    argstr='%s',
    ),
    bvals=dict(mandatory=True,
    ),
    out_file=dict(position=2,
    usedefault=True,
    argstr='%s',
    ),
    oblique_correction=dict(argstr='-oc',
    ),
    args=dict(argstr='%s',
    ),
    image_info=dict(argstr='-info %s',
    ),
    odf_file=dict(argstr='-odf %s',
    ),
    terminal_output=dict(mandatory=True,
    nohash=True,
    ),
    environ=dict(nohash=True,
    usedefault=True,
    ),
    image_orientation_vectors=dict(argstr='-iop %f',
    ),
    order=dict(argstr='-order %s',
    ),
    reference_file=dict(argstr='-ref %s',
    ),
    )
    inputs = HARDIMat.input_spec()

    for key, metadata in input_map.items():
        for metakey, value in metadata.items():
            yield assert_equal, getattr(inputs.traits()[key], metakey), value
def test_HARDIMat_outputs():
    output_map = dict(out_file=dict(),
    )
    outputs = HARDIMat.output_spec()

    for key, metadata in output_map.items():
        for metakey, value in metadata.items():
            yield assert_equal, getattr(outputs.traits()[key], metakey), value
