# AUTO-GENERATED by tools/checkspecs.py - DO NOT EDIT
from nipype.testing import assert_equal
from nipype.interfaces.diffusion_toolkit.odf import ODFTracker
def test_ODFTracker_inputs():
    input_map = dict(mask2_threshold=dict(position=5,
    ),
    input_data_prefix=dict(position=0,
    usedefault=True,
    argstr='%s',
    ),
    disc=dict(argstr='-disc',
    ),
    mask2_file=dict(position=4,
    argstr='-m2 %s',
    ),
    slice_order=dict(argstr='-sorder %d',
    ),
    invert_y=dict(argstr='-iy',
    ),
    invert_x=dict(argstr='-ix',
    ),
    invert_z=dict(argstr='-iz',
    ),
    swap_yz=dict(argstr='-syz',
    ),
    step_length=dict(argstr='-l %f',
    ),
    dsi=dict(argstr='-dsi',
    ),
    environ=dict(nohash=True,
    usedefault=True,
    ),
    ODF=dict(mandatory=True,
    ),
    ignore_exception=dict(nohash=True,
    usedefault=True,
    ),
    random_seed=dict(argstr='-rseed %s',
    ),
    max=dict(mandatory=True,
    ),
    args=dict(argstr='%s',
    ),
    voxel_order=dict(argstr='-vorder %s',
    ),
    terminal_output=dict(mandatory=True,
    nohash=True,
    ),
    mask1_file=dict(position=2,
    mandatory=True,
    argstr='-m %s',
    ),
    image_orientation_vectors=dict(argstr='-iop %f',
    ),
    out_file=dict(position=1,
    usedefault=True,
    argstr='%s',
    ),
    angle_threshold=dict(argstr='-at %f',
    ),
    swap_zx=dict(argstr='-szx',
    ),
    swap_xy=dict(argstr='-sxy',
    ),
    input_output_type=dict(usedefault=True,
    argstr='-it %s',
    ),
    runge_kutta2=dict(argstr='-rk2',
    ),
    limit=dict(argstr='-limit %d',
    ),
    mask1_threshold=dict(position=3,
    ),
    )
    inputs = ODFTracker.input_spec()

    for key, metadata in input_map.items():
        for metakey, value in metadata.items():
            yield assert_equal, getattr(inputs.traits()[key], metakey), value
def test_ODFTracker_outputs():
    output_map = dict(track_file=dict(),
    )
    outputs = ODFTracker.output_spec()

    for key, metadata in output_map.items():
        for metakey, value in metadata.items():
            yield assert_equal, getattr(outputs.traits()[key], metakey), value
