# AUTO-GENERATED by tools/checkspecs.py - DO NOT EDIT
from nipype.testing import assert_equal
from nipype.interfaces.freesurfer.preprocess import FitMSParams
def test_FitMSParams_inputs():
    input_map = dict(ignore_exception=dict(nohash=True,
    usedefault=True,
    ),
    flip_list=dict(),
    out_dir=dict(position=-1,
    genfile=True,
    argstr='%s',
    ),
    args=dict(argstr='%s',
    ),
    in_files=dict(argstr='%s',
    mandatory=True,
    position=-2,
    ),
    terminal_output=dict(mandatory=True,
    nohash=True,
    ),
    environ=dict(nohash=True,
    usedefault=True,
    ),
    xfm_list=dict(),
    subjects_dir=dict(),
    tr_list=dict(),
    te_list=dict(),
    )
    inputs = FitMSParams.input_spec()

    for key, metadata in input_map.items():
        for metakey, value in metadata.items():
            yield assert_equal, getattr(inputs.traits()[key], metakey), value
def test_FitMSParams_outputs():
    output_map = dict(t2star_image=dict(),
    pd_image=dict(),
    t1_image=dict(),
    )
    outputs = FitMSParams.output_spec()

    for key, metadata in output_map.items():
        for metakey, value in metadata.items():
            yield assert_equal, getattr(outputs.traits()[key], metakey), value
