# AUTO-GENERATED by tools/checkspecs.py - DO NOT EDIT
from nipype.testing import assert_equal
from nipype.interfaces.freesurfer.utils import SurfaceSmooth
def test_SurfaceSmooth_inputs():
    input_map = dict(ignore_exception=dict(nohash=True,
    usedefault=True,
    ),
    hemi=dict(mandatory=True,
    argstr='--hemi %s',
    ),
    out_file=dict(argstr='--tval %s',
    genfile=True,
    ),
    reshape=dict(argstr='--reshape',
    ),
    subject_id=dict(mandatory=True,
    argstr='--s %s',
    ),
    args=dict(argstr='%s',
    ),
    terminal_output=dict(mandatory=True,
    nohash=True,
    ),
    environ=dict(nohash=True,
    usedefault=True,
    ),
    in_file=dict(mandatory=True,
    argstr='--sval %s',
    ),
    smooth_iters=dict(xor=['fwhm'],
    argstr='--smooth %d',
    ),
    subjects_dir=dict(),
    fwhm=dict(xor=['smooth_iters'],
    argstr='--fwhm %.4f',
    ),
    cortex=dict(argstr='--cortex',
    usedefault=True,
    ),
    )
    inputs = SurfaceSmooth.input_spec()

    for key, metadata in input_map.items():
        for metakey, value in metadata.items():
            yield assert_equal, getattr(inputs.traits()[key], metakey), value
def test_SurfaceSmooth_outputs():
    output_map = dict(out_file=dict(),
    )
    outputs = SurfaceSmooth.output_spec()

    for key, metadata in output_map.items():
        for metakey, value in metadata.items():
            yield assert_equal, getattr(outputs.traits()[key], metakey), value
