# AUTO-GENERATED by tools/checkspecs.py - DO NOT EDIT
from nipype.testing import assert_equal
from nipype.interfaces.freesurfer.preprocess import Resample
def test_Resample_inputs():
    input_map = dict(ignore_exception=dict(nohash=True,
    usedefault=True,
    ),
    resampled_file=dict(position=-1,
    genfile=True,
    argstr='-o %s',
    ),
    args=dict(argstr='%s',
    ),
    voxel_size=dict(mandatory=True,
    argstr='-vs %.2f %.2f %.2f',
    ),
    terminal_output=dict(mandatory=True,
    nohash=True,
    ),
    environ=dict(nohash=True,
    usedefault=True,
    ),
    in_file=dict(position=-2,
    mandatory=True,
    argstr='-i %s',
    ),
    subjects_dir=dict(),
    )
    inputs = Resample.input_spec()

    for key, metadata in input_map.items():
        for metakey, value in metadata.items():
            yield assert_equal, getattr(inputs.traits()[key], metakey), value
def test_Resample_outputs():
    output_map = dict(resampled_file=dict(),
    )
    outputs = Resample.output_spec()

    for key, metadata in output_map.items():
        for metakey, value in metadata.items():
            yield assert_equal, getattr(outputs.traits()[key], metakey), value
