# AUTO-GENERATED by tools/checkspecs.py - DO NOT EDIT
from nipype.testing import assert_equal
from nipype.interfaces.freesurfer.utils import MakeAverageSubject
def test_MakeAverageSubject_inputs():
    input_map = dict(ignore_exception=dict(nohash=True,
    usedefault=True,
    ),
    args=dict(argstr='%s',
    ),
    terminal_output=dict(mandatory=True,
    nohash=True,
    ),
    environ=dict(nohash=True,
    usedefault=True,
    ),
    out_name=dict(argstr='--out %s',
    usedefault=True,
    ),
    subjects_dir=dict(),
    subjects_ids=dict(argstr='--subjects %s',
    mandatory=True,
    sep=' ',
    ),
    )
    inputs = MakeAverageSubject.input_spec()

    for key, metadata in input_map.items():
        for metakey, value in metadata.items():
            yield assert_equal, getattr(inputs.traits()[key], metakey), value
def test_MakeAverageSubject_outputs():
    output_map = dict(average_subject_name=dict(),
    )
    outputs = MakeAverageSubject.output_spec()

    for key, metadata in output_map.items():
        for metakey, value in metadata.items():
            yield assert_equal, getattr(outputs.traits()[key], metakey), value
