# AUTO-GENERATED by tools/checkspecs.py - DO NOT EDIT
from nipype.testing import assert_equal
from nipype.interfaces.freesurfer.utils import MRIsConvert
def test_MRIsConvert_inputs():
    input_map = dict(out_datatype=dict(mandatory=True,
    ),
    scale=dict(argstr='-s %.3f',
    ),
    functional_file=dict(argstr='-f %s',
    ),
    labelstats_outfile=dict(argstr='--labelstats %s',
    ),
    in_file=dict(position=-2,
    mandatory=True,
    argstr='%s',
    ),
    talairachxfm_subjid=dict(argstr='-t %s',
    ),
    ignore_exception=dict(nohash=True,
    usedefault=True,
    ),
    origname=dict(argstr='-o %s',
    ),
    normal=dict(argstr='-n',
    ),
    rescale=dict(argstr='-r',
    ),
    args=dict(argstr='%s',
    ),
    vertex=dict(argstr='-v',
    ),
    terminal_output=dict(mandatory=True,
    nohash=True,
    ),
    subjects_dir=dict(),
    xyz_ascii=dict(argstr='-a',
    ),
    out_file=dict(position=-1,
    genfile=True,
    argstr='./%s',
    ),
    patch=dict(argstr='-p',
    ),
    environ=dict(nohash=True,
    usedefault=True,
    ),
    label_file=dict(argstr='--label %s',
    ),
    parcstats_file=dict(argstr='--parcstats %s',
    ),
    annot_file=dict(argstr='--annot %s',
    ),
    scalarcurv_file=dict(argstr='-c %s',
    ),
    dataarray_num=dict(argstr='--da_num %d',
    ),
    )
    inputs = MRIsConvert.input_spec()

    for key, metadata in input_map.items():
        for metakey, value in metadata.items():
            yield assert_equal, getattr(inputs.traits()[key], metakey), value
def test_MRIsConvert_outputs():
    output_map = dict(converted=dict(),
    )
    outputs = MRIsConvert.output_spec()

    for key, metadata in output_map.items():
        for metakey, value in metadata.items():
            yield assert_equal, getattr(outputs.traits()[key], metakey), value
