# AUTO-GENERATED by tools/checkspecs.py - DO NOT EDIT
from nipype.testing import assert_equal
from nipype.interfaces.freesurfer.utils import SurfaceTransform
def test_SurfaceTransform_inputs():
    input_map = dict(ignore_exception=dict(nohash=True,
    usedefault=True,
    ),
    hemi=dict(mandatory=True,
    argstr='--hemi %s',
    ),
    out_file=dict(argstr='--tval %s',
    genfile=True,
    ),
    source_subject=dict(mandatory=True,
    argstr='--srcsubject %s',
    ),
    reshape=dict(argstr='--reshape',
    ),
    args=dict(argstr='%s',
    ),
    target_ico_order=dict(argstr='--trgicoorder %d',
    ),
    target_type=dict(argstr='--tfmt %s',
    ),
    reshape_factor=dict(argstr='--reshape-factor',
    ),
    source_type=dict(requires=['source_file'],
    argstr='--sfmt %s',
    ),
    terminal_output=dict(mandatory=True,
    nohash=True,
    ),
    environ=dict(nohash=True,
    usedefault=True,
    ),
    subjects_dir=dict(),
    source_file=dict(mandatory=True,
    argstr='--sval %s',
    xor=['source_annot_file'],
    ),
    target_subject=dict(mandatory=True,
    argstr='--trgsubject %s',
    ),
    source_annot_file=dict(mandatory=True,
    argstr='--sval-annot %s',
    xor=['source_file'],
    ),
    )
    inputs = SurfaceTransform.input_spec()

    for key, metadata in input_map.items():
        for metakey, value in metadata.items():
            yield assert_equal, getattr(inputs.traits()[key], metakey), value
def test_SurfaceTransform_outputs():
    output_map = dict(out_file=dict(),
    )
    outputs = SurfaceTransform.output_spec()

    for key, metadata in output_map.items():
        for metakey, value in metadata.items():
            yield assert_equal, getattr(outputs.traits()[key], metakey), value
