# Copyright (c) 2016, The developers of nipype
# All rights reserved.
#
# Redistribution and use in source and binary forms, with or without
# modification, are permitted provided that the following conditions are met:
#
# * Redistributions of source code must retain the above copyright notice, this
#   list of conditions and the following disclaimer.
#
# * Redistributions in binary form must reproduce the above copyright notice,
#   this list of conditions and the following disclaimer in the documentation
#   and/or other materials provided with the distribution.
#
# * Neither the name of crn_base nor the names of its
#   contributors may be used to endorse or promote products derived from
#   this software without specific prior written permission.
#
# THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS"
# AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE
# IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE
# DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT HOLDER OR CONTRIBUTORS BE LIABLE
# FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL
# DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR
# SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER
# CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY,
# OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE
# OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.

FROM nipype/nipype_test:base-0.0.2
MAINTAINER The nipype developers https://github.com/nipy/nipype

# Downgrade python to 3.4
RUN conda update -y conda && \
    conda update --all -y python=3.4

COPY docker/circleci/run_* /usr/bin/
RUN chmod +x /usr/bin/run_*

# Replace imglob with a Python3 compatible version
COPY nipype/external/fsl_imglob.py /usr/bin/fsl_imglob.py
RUN rm -r ${FSLDIR}/bin/imglob && \
    chmod +x /usr/bin/fsl_imglob.py && \
    ln -s /usr/bin/fsl_imglob.py ${FSLDIR}/bin/imglob

# Speed up building
RUN mkdir -p /root/src/nipype
COPY requirements.txt /root/src/nipype/requirements.txt
RUN pip install -r /root/src/nipype/requirements.txt

# Re-install nipype
COPY . /root/src/nipype
RUN rm -r /usr/local/miniconda/lib/python3.4/site-packages/nipype* && \
    cd /root/src/nipype && \
    pip install -e . 

CMD ["/bin/bash"]
