# Copyright (c) 2016, The developers of nipype
# All rights reserved.
#
# Redistribution and use in source and binary forms, with or without
# modification, are permitted provided that the following conditions are met:
#
# * Redistributions of source code must retain the above copyright notice, this
#   list of conditions and the following disclaimer.
#
# * Redistributions in binary form must reproduce the above copyright notice,
#   this list of conditions and the following disclaimer in the documentation
#   and/or other materials provided with the distribution.
#
# * Neither the name of crn_base nor the names of its
#   contributors may be used to endorse or promote products derived from
#   this software without specific prior written permission.
#
# THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS"
# AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE
# IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE
# DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT HOLDER OR CONTRIBUTORS BE LIABLE
# FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL
# DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR
# SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER
# CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY,
# OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE
# OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.

FROM gawbul/docker-sge:latest
MAINTAINER Nipype developers

# Preparations
ARG DEBIAN_FRONTEND=noninteractive
RUN apt-get -y update && \
    apt-get install -y curl \
                       git \
                       xvfb \
                       bzip2 \
                       unzip \
                       apt-utils \
                       fusefat \
                       graphviz \
                       make \
                       ruby && \
    rm -rf /var/lib/apt/lists/* /tmp/* /var/tmp/*

WORKDIR /opt
RUN wget  --retry-connrefused --waitretry=5 --read-timeout=20 --timeout=15 -t 0 -q https://2a353b13e8d2d9ac21ce543b7064482f771ce658.googledrive.com/host/0BxI12kyv2olZVFhUcGVpYWF3R3c/FSL-5.0.9-centos6_64.tar.gz && \
    tar xzf FSL-5.0.9-centos6_64.tar.gz -C /opt/

# Set FSL environment variables
ENV FSLDIR=/opt/fsl \
    FSLOUTPUTTYPE=NIFTI_GZ \
    FSLMULTIFILEQUIT=TRUE \
    POSSUMDIR=/opt/fsl \
    FSLTCLSH=/usr/bin/tclsh \
    FSLWISH=/usr/bin/wish \
    PATH=/opt/fsl/bin:$PATH \
    LD_LIBRARY_PATH=/opt/fsl/lib:$LD_LIBRARY_PATH

# Install fake-S3
ENV GEM_HOME /usr/local/bundle
ENV BUNDLE_PATH="$GEM_HOME" \
    BUNDLE_BIN="$GEM_HOME/bin" \
    BUNDLE_SILENCE_ROOT_WARNING=1 \
    BUNDLE_APP_CONFIG="$GEM_HOME"
ENV PATH $BUNDLE_BIN:$PATH
RUN mkdir -p "$GEM_HOME" "$BUNDLE_BIN" && \
    chmod 777 "$GEM_HOME" "$BUNDLE_BIN"

RUN gem install fakes3

# # Install Matlab MCR: from the good old install_spm_mcr.sh of @chrisfilo
# RUN echo "destinationFolder=/opt/mcr" > mcr_options.txt && \
#     echo "agreeToLicense=yes" >> mcr_options.txt && \
#     echo "outputFile=/tmp/matlabinstall_log" >> mcr_options.txt && \
#     echo "mode=silent" >> mcr_options.txt && \
#     mkdir -p matlab_installer && \
#     curl -sSL http://www.mathworks.com/supportfiles/downloads/R2015a/deployment_files/R2015a/installers/glnxa64/MCR_R2015a_glnxa64_installer.zip \
#          -o matlab_installer/installer.zip && \
#     unzip matlab_installer/installer.zip -d matlab_installer/ && \
#     matlab_installer/install -inputFile mcr_options.txt && \
#     rm -rf matlab_installer mcr_options.txt
# 
# # Install SPM
# RUN curl -sSL http://www.fil.ion.ucl.ac.uk/spm/download/restricted/utopia/dev/spm12_r6472_Linux_R2015a.zip -o spm12.zip && \
#     unzip spm12.zip && \
#     rm -rf spm12.zip
# 
# ENV MATLABCMD="/opt/mcr/v85/toolbox/matlab" \
#     SPMMCRCMD="/opt/spm12/run_spm12.sh /opt/mcr/v85/ script" \
#     FORCE_SPMMCR=1

CMD ["/bin/bash"]
