# AUTO-GENERATED by tools/checkspecs.py - DO NOT EDIT
from nipype.testing import assert_equal
from nipype.interfaces.mrtrix.tracking import Tracks2Prob
def test_Tracks2Prob_inputs():
    input_map = dict(out_filename=dict(position=-1,
    genfile=True,
    argstr='%s',
    ),
    ignore_exception=dict(nohash=True,
    usedefault=True,
    ),
    template_file=dict(position=1,
    argstr='-template %s',
    ),
    resample=dict(units='mm',
    position=3,
    argstr='-resample %d',
    ),
    colour=dict(position=3,
    argstr='-colour',
    ),
    args=dict(argstr='%s',
    ),
    terminal_output=dict(mandatory=True,
    nohash=True,
    ),
    environ=dict(nohash=True,
    usedefault=True,
    ),
    in_file=dict(position=-2,
    mandatory=True,
    argstr='%s',
    ),
    fraction=dict(position=3,
    argstr='-fraction',
    ),
    voxel_dims=dict(argstr='-vox %s',
    sep=',',
    position=2,
    ),
    output_datatype=dict(position=2,
    argstr='-datatype %s',
    ),
    )
    inputs = Tracks2Prob.input_spec()

    for key, metadata in input_map.items():
        for metakey, value in metadata.items():
            yield assert_equal, getattr(inputs.traits()[key], metakey), value
def test_Tracks2Prob_outputs():
    output_map = dict(tract_image=dict(),
    )
    outputs = Tracks2Prob.output_spec()

    for key, metadata in output_map.items():
        for metakey, value in metadata.items():
            yield assert_equal, getattr(outputs.traits()[key], metakey), value
