# AUTO-GENERATED by tools/checkspecs.py - DO NOT EDIT
from nipype.testing import assert_equal
from nipype.interfaces.mrtrix.tensors import Directions2Amplitude
def test_Directions2Amplitude_inputs():
    input_map = dict(ignore_exception=dict(nohash=True,
    usedefault=True,
    ),
    out_file=dict(hash_files=False,
    keep_extension=False,
    name_source=['in_file'],
    name_template='%s_amplitudes.mif',
    position=-1,
    argstr='%s',
    ),
    quiet_display=dict(argstr='-quiet',
    ),
    args=dict(argstr='%s',
    ),
    num_peaks=dict(argstr='-num %s',
    ),
    display_info=dict(argstr='-info',
    ),
    display_debug=dict(argstr='-debug',
    ),
    environ=dict(nohash=True,
    usedefault=True,
    ),
    in_file=dict(position=-2,
    mandatory=True,
    argstr='%s',
    ),
    peak_directions=dict(sep=' ',
    argstr='-direction %s',
    ),
    peaks_image=dict(argstr='-peaks %s',
    ),
    terminal_output=dict(mandatory=True,
    nohash=True,
    ),
    )
    inputs = Directions2Amplitude.input_spec()

    for key, metadata in input_map.items():
        for metakey, value in metadata.items():
            yield assert_equal, getattr(inputs.traits()[key], metakey), value
def test_Directions2Amplitude_outputs():
    output_map = dict(out_file=dict(),
    )
    outputs = Directions2Amplitude.output_spec()

    for key, metadata in output_map.items():
        for metakey, value in metadata.items():
            yield assert_equal, getattr(outputs.traits()[key], metakey), value
