# AUTO-GENERATED by tools/checkspecs.py - DO NOT EDIT
from ..tracking import FilterTracks


def test_FilterTracks_inputs():
    input_map = dict(args=dict(argstr='%s',
    ),
    debug=dict(argstr='-debug',
    position=1,
    ),
    environ=dict(nohash=True,
    usedefault=True,
    ),
    exclude_file=dict(argstr='-exclude %s',
    xor=[u'exclude_file', u'exclude_spec'],
    ),
    exclude_spec=dict(argstr='-exclude %s',
    position=2,
    sep=',',
    units='mm',
    xor=[u'exclude_file', u'exclude_spec'],
    ),
    ignore_exception=dict(nohash=True,
    usedefault=True,
    ),
    in_file=dict(argstr='%s',
    mandatory=True,
    position=-2,
    ),
    include_file=dict(argstr='-include %s',
    xor=[u'include_file', u'include_spec'],
    ),
    include_spec=dict(argstr='-include %s',
    position=2,
    sep=',',
    units='mm',
    xor=[u'include_file', u'include_spec'],
    ),
    invert=dict(argstr='-invert',
    ),
    minimum_tract_length=dict(argstr='-minlength %s',
    units='mm',
    ),
    no_mask_interpolation=dict(argstr='-nomaskinterp',
    ),
    out_file=dict(argstr='%s',
    hash_files=False,
    name_source=[u'in_file'],
    name_template='%s_filt',
    position=-1,
    ),
    quiet=dict(argstr='-quiet',
    position=1,
    ),
    terminal_output=dict(nohash=True,
    ),
    )
    inputs = FilterTracks.input_spec()

    for key, metadata in list(input_map.items()):
        for metakey, value in list(metadata.items()):
            assert getattr(inputs.traits()[key], metakey) == value


def test_FilterTracks_outputs():
    output_map = dict(out_file=dict(),
    )
    outputs = FilterTracks.output_spec()

    for key, metadata in list(output_map.items()):
        for metakey, value in list(metadata.items()):
            assert getattr(outputs.traits()[key], metakey) == value
