# AUTO-GENERATED by tools/checkspecs.py - DO NOT EDIT
from ..cat_surf import CatSurfSulcusDepth


def test_CatSurfSulcusDepth_inputs():
    input_map = dict(
        faces=dict(
            mandatory=True,
        ),
        vertices=dict(
            mandatory=True,
        ),
    )
    inputs = CatSurfSulcusDepth.input_spec()

    for key, metadata in list(input_map.items()):
        for metakey, value in list(metadata.items()):
            assert getattr(inputs.traits()[key], metakey) == value


def test_CatSurfSulcusDepth_outputs():
    output_map = dict(
        depth=dict(),
    )
    outputs = CatSurfSulcusDepth.output_spec()

    for key, metadata in list(output_map.items()):
        for metakey, value in list(metadata.items()):
            assert getattr(outputs.traits()[key], metakey) == value
