# AUTO-GENERATED by tools/checkspecs.py - DO NOT EDIT
from ..cat_surf import CatSurfPointDistanceMean


def test_CatSurfPointDistanceMean_inputs():
    input_map = dict(
        faces1=dict(
            mandatory=True,
        ),
        faces2=dict(
            mandatory=True,
        ),
        max_dist=dict(
            usedefault=True,
        ),
        symmetric=dict(
            usedefault=True,
        ),
        vertices1=dict(
            mandatory=True,
        ),
        vertices2=dict(
            mandatory=True,
        ),
    )
    inputs = CatSurfPointDistanceMean.input_spec()

    for key, metadata in list(input_map.items()):
        for metakey, value in list(metadata.items()):
            assert getattr(inputs.traits()[key], metakey) == value


def test_CatSurfPointDistanceMean_outputs():
    output_map = dict(
        distances=dict(),
        mean_distance=dict(),
    )
    outputs = CatSurfPointDistanceMean.output_spec()

    for key, metadata in list(output_map.items()):
        for metakey, value in list(metadata.items()):
            assert getattr(outputs.traits()[key], metakey) == value
