# AUTO-GENERATED by tools/checkspecs.py - DO NOT EDIT
from ..cat_surf import CatSurfToPialWhite


def test_CatSurfToPialWhite_inputs():
    input_map = dict(
        faces=dict(
            mandatory=True,
        ),
        gradient_iterations=dict(
            usedefault=True,
        ),
        iterations=dict(
            usedefault=True,
        ),
        method=dict(
            usedefault=True,
        ),
        sigma=dict(
            usedefault=True,
        ),
        thickness=dict(
            mandatory=True,
        ),
        verbose=dict(
            usedefault=True,
        ),
        vertices=dict(
            mandatory=True,
        ),
        volume_file=dict(
            extensions=None,
            mandatory=True,
        ),
        w1=dict(
            usedefault=True,
        ),
        w2=dict(
            usedefault=True,
        ),
        w3=dict(
            usedefault=True,
        ),
    )
    inputs = CatSurfToPialWhite.input_spec()

    for key, metadata in list(input_map.items()):
        for metakey, value in list(metadata.items()):
            assert getattr(inputs.traits()[key], metakey) == value


def test_CatSurfToPialWhite_outputs():
    output_map = dict(
        pial_faces=dict(),
        pial_vertices=dict(),
        white_faces=dict(),
        white_vertices=dict(),
    )
    outputs = CatSurfToPialWhite.output_spec()

    for key, metadata in list(output_map.items()):
        for metakey, value in list(metadata.items()):
            assert getattr(outputs.traits()[key], metakey) == value
