# AUTO-GENERATED by tools/checkspecs.py - DO NOT EDIT
from nipype.testing import assert_equal
from nipype.interfaces.io import XNATSink
def test_XNATSink_inputs():
    input_map = dict(ignore_exception=dict(nohash=True,
    usedefault=True,
    ),
    _outputs=dict(usedefault=True,
    ),
    subject_id=dict(mandatory=True,
    ),
    share=dict(usedefault=True,
    ),
    server=dict(xor=['config'],
    mandatory=True,
    requires=['user', 'pwd'],
    ),
    reconstruction_id=dict(xor=['assessor_id'],
    ),
    pwd=dict(),
    cache_dir=dict(),
    assessor_id=dict(xor=['reconstruction_id'],
    ),
    user=dict(),
    experiment_id=dict(mandatory=True,
    ),
    project_id=dict(mandatory=True,
    ),
    config=dict(mandatory=True,
    xor=['server'],
    ),
    )
    inputs = XNATSink.input_spec()

    for key, metadata in input_map.items():
        for metakey, value in metadata.items():
            yield assert_equal, getattr(inputs.traits()[key], metakey), value
