# AUTO-GENERATED by tools/checkspecs.py - DO NOT EDIT
from nipype.testing import assert_equal
from nipype.interfaces.ants.utils import AverageImages
def test_AverageImages_inputs():
    input_map = dict(normalize=dict(position=2,
    mandatory=True,
    argstr='%d',
    ),
    num_threads=dict(nohash=True,
    usedefault=True,
    ),
    ignore_exception=dict(nohash=True,
    usedefault=True,
    ),
    args=dict(argstr='%s',
    ),
    output_average_image=dict(hash_files=False,
    usedefault=True,
    position=1,
    argstr='%s',
    ),
    terminal_output=dict(mandatory=True,
    nohash=True,
    ),
    environ=dict(nohash=True,
    usedefault=True,
    ),
    images=dict(argstr='%s',
    mandatory=True,
    position=3,
    ),
    dimension=dict(position=0,
    mandatory=True,
    argstr='%d',
    ),
    )
    inputs = AverageImages.input_spec()

    for key, metadata in input_map.items():
        for metakey, value in metadata.items():
            yield assert_equal, getattr(inputs.traits()[key], metakey), value
def test_AverageImages_outputs():
    output_map = dict(output_average_image=dict(),
    )
    outputs = AverageImages.output_spec()

    for key, metadata in output_map.items():
        for metakey, value in metadata.items():
            yield assert_equal, getattr(outputs.traits()[key], metakey), value
