name: Tox

on:
  push:
    branches: [ master, main, 'maint/*' ]
    tags: [ '*' ]
  pull_request:
    branches: [ master, main, 'maint/*' ]
  schedule:
    # 8am EST / 9am EDT Mondays
    - cron: "0 13 * * 1"

defaults:
  run:
    shell: bash

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

permissions:
  contents: read

env:
  # Force tox and pytest to use color
  FORCE_COLOR: true


jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
        with:
          fetch-depth: 0
      - name: Install the latest version of uv
        uses: astral-sh/setup-uv@20cfd1bf945f4377ade1205e4dbc17946fc9a30d # v10.0.1
      - run: uv build
      - run: uvx twine check dist/*
      - uses: actions/upload-artifact@043fb46d1a93c77aae656e7c1c64a875d1fc6a0a # v7.0.1
        with:
          name: dist
          path: dist/

  test-package:
    runs-on: ubuntu-latest
    needs: [build]
    strategy:
      matrix:
        package: ["wheel", "sdist"]
    steps:
      - uses: actions/download-artifact@3e5f45b2cfb9172054b4087a40e8e0b5a5461e7c # v8.0.1
        with:
          name: dist
          path: dist/
      - name: Verify artifacts are present
        run: |
          ls -l . dist/
          wheel_file=$(find dist -name 'nipype-*.whl' | head -n 1)
          tar_file=$(find dist -name 'nipype-*.tar.gz' | head -n 1)

          echo "WHEEL=$wheel_file" >> $GITHUB_ENV
          echo "SDIST=$tar_file" >> $GITHUB_ENV
      - name: Install Python
        uses: actions/setup-python@5fda3b95a4ea91299a34e894583c3862153e4b97 # v7.0.0
        with:
          python-version: "3.13"
      - name: Display Python version
        run: python -c "import sys; print(sys.version)"
      - name: Install wheel
        run: pip install $WHEEL[tests]
        if: matrix.package == 'wheel'
      - name: Install sdist
        run: pip install $SDIST[tests]
        if: matrix.package == 'sdist'
      - name: Display nipype version
        run: python -c 'import nipype; print(nipype.__version__)'
      - name: Run tests
        run: pytest --doctest-modules -v --pyargs nipype

  test:
    # Check each OS, all supported Python, minimum versions and latest releases
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: ["ubuntu-latest"]
        python-version: ["3.10", "3.11", "3.12", "3.13", "3.14"]
        dependencies: [none, full]
        include:
          - os: ubuntu-latest
            python-version: "3.10"
            dependencies: min
        exclude:
          # Skip some intermediate versions for full tests
          - python-version: "3.11"
            dependencies: full
          - python-version: "3.12"
            dependencies: full

    env:
      DEPENDS: ${{ matrix.dependencies }}

    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
        with:
          fetch-depth: 0
      - name: Install the latest version of uv
        uses: astral-sh/setup-uv@20cfd1bf945f4377ade1205e4dbc17946fc9a30d # v10.0.1
        with:
          python-version: ${{ matrix.python-version }}
      - name: Display Python version
        run: python -c "import sys; print(sys.version)"
      - name: Install tox
        run: |
          uv tool install --with=tox-uv --with=tox-gh-actions tox
      - name: Show tox config
        run: tox c
      - name: Setup test suite
        run: tox run -vv --notest
      - name: Run tox
        run: tox -v --skip-pkg-install --exit-and-dump-after 1200
      - uses: codecov/codecov-action@fb8b3582c8e4def4969c97caa2f19720cb33a72f # v7.0.0
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
        if: ${{ always() }}
      - name: Upload pytest test results
        uses: actions/upload-artifact@043fb46d1a93c77aae656e7c1c64a875d1fc6a0a # v7.0.1
        with:
          name: pytest-results-${{ matrix.os }}-${{ matrix.python-version }}-${{ matrix.dependencies }}
          path: test-results.xml
        if: always()

  publish:
    runs-on: ubuntu-latest
    environment: "Package deployment"
    needs: [test, test-package]
    if: github.event_name == 'push' && startsWith(github.ref, 'refs/tags/')
    steps:
      - uses: actions/download-artifact@3e5f45b2cfb9172054b4087a40e8e0b5a5461e7c # v8.0.1
        with:
          name: dist
          path: dist/
      - uses: pypa/gh-action-pypi-publish@dc37677b2e1c63e2034f94d8a5b11f265b73ba33 # v1.14.2
        with:
          user: __token__
          password: ${{ secrets.PYPI_API_TOKEN }}

  checks:
    runs-on: 'ubuntu-latest'
    continue-on-error: true
    strategy:
      matrix:
        check: ['specs', 'style']

    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
      - name: Install the latest version of uv
        uses: astral-sh/setup-uv@20cfd1bf945f4377ade1205e4dbc17946fc9a30d # v10.0.1
      - name: Install tox
        run: uv tool install --with=tox-uv tox
      - name: Show tox config (this call)
        run: tox c -e ${{ matrix.check }}
      - name: Run check
        run: tox -e ${{ matrix.check }}
